version: '3'
services:
  demo-site.pv:
    container_name: demo-site.pv
    image: pagevamp/nginx-php7-fpm:7.2
    restart: always
    environment:
      - VIRTUAL_HOST=demo-site.pv
    volumes:
      - ./:/var/www
      - ./docker/sites/default.conf:/etc/nginx/sites-enabled/default
    networks:
      - pagevamp
networks:
  pagevamp:
    external: true
